KLTN/Areas/GVHD/Models/DeTaiNghienCuuViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KLTN.Areas.GVHD.Models
{
    public class DeTaiNghienCuuViewModel
    {
        public string NgayLap { get; set; }

        public long Id { get; set; }
        [Required(ErrorMessage = "Tên đề tài không được trống")]
        public string TenDeTai { get; set; }
        public long? IdgiangVien { get; set; }
        public string Mssv { get; set; }
        public string MoTa { get; set; }
        public string TepDinhKem { get; set; }
        public bool? Loai { get; set; }
        public string TenTep { get; set; }
        public string HoTenGVHD { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TinhTrangDangKy { get; set; }
        public string TinhTrangPheDuyet { get; set; }
        public string TinhTrangDeTai { get; set; }

        public IFormFile Files { get; set; }

        
    }
}

KLTN/Areas/Admin/Controllers/DeTaiNghienCuuController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Data.Enum;
using Data.Interfaces;
using Data.Models;
using KLTN.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;

namespace KLTN.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DeTaiNghienCuuController : Controller
    {
        private readonly IDeTaiNghienCuu _service;
        private readonly IMoDot _serviceMoDot;
        private readonly INhomSinhVien _serviceNhomSV;
        private readonly IXetDuyetDanhGia _serviceXetDuyet;
        private readonly IctXetDuyetDanhGia _serviceCTXetDuyetVaDanhGia;
        private readonly IGiangVien _serviceGiangVien;
        public DeTaiNghienCuuController(IDeTaiNghienCuu service, IMoDot serviceMoDot, INhomSinhVien serviceNhomSV
                                        , IXetDuyetDanhGia serviceXetDuyet, IctXetDuyetDanhGia serviceCTXetDuyetVaDanhGia
                                        , IGiangVien serviceGiangVien)
        {
            _service = service;
            _serviceMoDot = serviceMoDot;
            _serviceNhomSV = serviceNhomSV;
            _serviceXetDuyet = serviceXetDuyet;
            _serviceCTXetDuyetVaDanhGia = serviceCTXetDuyetVaDanhGia;
            _serviceGiangVien = serviceGiangVien;
        }
        public async Task<IActionResult> Index(string mess)
        {
            IEnumerable<MoDot> listDotDangKy = await _serviceMoDot.GetAll(x => x.Loai == (int)MoDotLoai.DangKy);
            if(!listDotDangKy.Any())
            {
                return View();
            }
            MoDot DotDangKyMoiNhat =  listDotDangKy.ToList().LastOrDefault();

            IEnumerable<DeTaiNghienCuu> listDeTaiHienTai = await _service.GetAll(x => x.TinhTrangDeTai == (int)StatusDeTai.DaDuyet 
                                                                                 || x.TinhTrangDeTai == (int)StatusDeTai.DaDangKy
                                                                                 || x.TinhTrangDeTai == (int)StatusDeTai.HoanThanh
                                                                                 || x.TinhTrangDeTai == (int)StatusDeTai.Huy
                                                                                 && (x.NgayDangKy > DotDangKyMoiNhat.ThoiGianBd && x.NgayDangKy < DotDangKyMoiNhat.ThoiGianKt)
                                                                                 || (x.NgayDangKy == null && x.TinhTrangDeTai == (int)StatusDeTai.DaDuyet));
            IEnumerable<DeTaiNghienCuu> listDeTaiDeXuatHienTai = await _service.GetAll(x => x.Loai == LoaiDeTai.DeXuat
                                                                                       && x.NgayDangKy > DotDangKyMoiNhat.ThoiGianBd
                                                                                       && x.NgayDangKy < DotDangKyMoiNhat.ThoiGianKt);
            IEnumerable<GiangVien> listGiangVien = await _serviceGiangVien.GetAll();

            DeTaiNghienCuuAdminViewModel viewModel = new DeTaiNghienCuuAdminViewModel() {
                DotDangKyHienTai = DotDangKyMoiNhat,
                listDeTaiHienTai = listDeTaiHienTai,
                listDeTaiDeXuatHienTai = listDeTaiDeXuatHienTai,
                listGiangVien = listGiangVien.Select(a => new SelectListItem()
                {
                    Value = a.Id.ToString(),
                    Text = a.Ho + " " + a.Ten
                }).ToList()
            };

            if (mess != "")
            {
                ViewBag.mess = mess;
            }

            return View(viewModel);
        }

        public async Task<IActionResult> XuatBaoCaoTongQuat()
        {
            IEnumerable<MoDot> listDotDangKy = await _serviceMoDot.GetAll(x => x.Loai == (int)MoDotLoai.DangKy);
            MoDot DotDangKyMoiNhat = listDotDangKy.ToList().Last();

            IEnumerable<DeTaiNghienCuu> listDeTaiHienTai = await _service.GetAll(x => x.TinhTrangDeTai != (int)StatusDeTai.MoiTao
                                                                                 && (x.NgayDangKy > DotDangKyMoiNhat.ThoiGianBd
                                                                                 && x.NgayDangKy < DotDangKyMoiNhat.ThoiGianKt)
                                                                                 || (x.NgayDangKy == null && x.TinhTrangDeTai == (int)StatusDeTai.DaDuyet));
            
            List<DeTaiNghienCuu> listDeTaiDaDangKy = listDeTaiHienTai.Where(x => x.TinhTrangDangKy == (int)StatusDangKyDeTai.Het).ToList();

            List<DeTaiNghienCuu> listDeTaiChuaDangKy = listDeTaiHienTai.Where(x => x.TinhTrangDeTai != (int)StatusDeTai.MoiTao && x.TinhTrangDangKy == (int)StatusDangKyDeTai.Con).ToList();

            var stream = new MemoryStream();

            using (var package = new ExcelPackage(stream))
            {
                #region -- Danh sách đề tài được mở --
                    var Sheet1 = package.Workbook.Worksheets.Add("Danh sách đề tài được mở");

                    #region -- Header --

                    Sheet1.Cells["A1"].Style.Font.Bold = true;
                    Sheet1.Cells["A1"].Value = "TRƯỜNG ĐẠI HỌC SÀI GÒN";
                    Sheet1.Cells["E1"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Right;
                    Sheet1.Cells["E1"].Value = DateTime.Now.ToString("HH:mm, dd/MM/yyyy");
                    Sheet1.Cells["A3:E3"].Merge = true;
                    Sheet1.Cells["A3"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                    Sheet1.Cells["A3"].Style.Font.Bold = true;
                    Sheet1.Cells["A3"].Value = "BÁO CÁO TỔNG QUÁT ĐỀ TÀI NGHIÊN CỨU";

                    Sheet1.Cells["A5"].Style.Font.Bold = true;
                    Sheet1.Cells["A5"].Value = "Danh sách đề tài được mở";

                    Sheet1.Cells["A7:E7"].Style.Font.Bold = true;
                    Sheet1.Cells["A7:E7"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                    Sheet1.Cells["A7"].Value = "Mã đề tài";
                    Sheet1.Cells["B7"].Value = "Tên đề tài";
                    Sheet1.Cells["C7"].Value = "Mô tả";
                    Sheet1.Cells["D7"].Value = "Ngày lập";
                    Sheet1.Cells["E7"].Value = "Giảng viên";

                    #endregion

                    #region -- Details --
                    int rowSheet1 = 8;
                    foreach (var item in listDeTaiHienTai)
                    {
                        Sheet1.Cells[string.Format("A{0}", rowSheet1)].Value = item.Id;
                        Sheet1.Cells[string.Format("B{0}", rowSheet1)].Value = item.TenDeTai;
                        Sheet1.Cells[string.Format("C{0}", rowSheet1)].Value = item.MoTa;
                        Sheet1.Cells[string.Format("D{0}", rowSheet1)].Value = item.NgayLap.Value.ToString("dd/MM/yyyy");
                        if(item.IdgiangVien != null)
                        {
                            Sheet1.Cells[string.Format("E{0}", rowSheet1)].Value = item.IdgiangVienNavigation.Ho + " " + item.IdgiangVienNavigation.Ten;
                        }
                        
                        rowSheet1++;
                    }
                    #endregion

                    #region -- Footer --


                    Sheet1.Cells["A7" + ":" + string.Format("E{0}", rowSheet1 - 1)].Style.Border.Top.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                    Sheet1.Cells["A7" + ":" + string.Format("E{0}", rowSheet1 - 1)].Style.Border.Bottom.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                    Sheet1.Cells["A7" + ":" + string.Format("E{0}", rowSheet1 - 1)].Style.Border.Left.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;
                    Sheet1.Cells["A7" + ":" + string.Format("E{0}", rowSheet1 - 1)].Style.Border.Right.Style = OfficeOpenXml.Style.ExcelBorderStyle.Thin;

                    Sheet1.Cells["A:AZ"].AutoFitColumns();
                    #endregion
                #endregion

                #region -- Danh sách đề tài đã đăng ký --
                var Sheet2 = package.Workbook.Worksheets.Add("Danh sách đề tài đã đăng ký");

                #region -- Header --

                Sheet2.Cells["A1"].Style.Font.Bold = true;
                Sheet2.Cells["A1"].Value = "Danh sách đề tài đã đăng ký";

                Sheet2.Cells["A3:I3"].Style.Font.Bold = true;
                Sheet1.Cells["A3:I3"].Style.HorizontalAlignment = OfficeOpenXml.Style.ExcelHorizontalAlignment.Center;
                Sheet2.Cells["A3"].Value = "Mã đề tài";
                Sheet2.Cells["B3"].Value = "Tên đề tài";
                Sheet2.Cells["C3"].Value = "Mô tả";
                Sheet2.Cells["D3"].Value = "Ngày lập";
                Sheet2.Cells["E3"].Value = "Sinh viên đăng ký";
                Sheet2.Cells["F3"].Value = "Giảng viên";
                Sheet2.Cells["G3"].Value = "Hội đồng xét duyệt";
                Sheet2.Cells["H3"].Value = "Hội đồng đánh giá nghiệm thu";
                Sheet2.Cells["I3"].Value = "Trạng thái";

                #endregion

                #region -- Details --
                int rowSheet2 = 4;
                foreach (var item in listDeTaiDaDangKy)
                {
                    Sheet2.Cells[string.Format("A{0}", rowSheet2)].Value = item.Id;
                    Sheet2.Cells[string.Format("B{0}", rowSheet2)].Value = item.TenDeTai;
                    Sheet2.Cells[string.Format("C{0}", rowSheet2)].Value = item.MoTa;
                    Sheet2.Cells[string.Format("D{0}", rowSheet2)].Value = item.NgayLap.Value.ToString("dd/MM/yyyy");
                    Sheet2.Cells[string.Format("E{0}", rowSheet2)].Value = ThanhVienNhom(item.Id).Result;
                    if(item.IdgiangVien != null)
                    {

KLTN/Areas/Admin/Views/DeTaiNghienCuu/Index.cshtml
@model KLTN.Areas.Admin.Models.DeTaiNghienCuuAdminViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Script
{
    <script>
        $(document).ready(function () {
            $(document).on("click", ".btnPhanCong", function () {
                $("#IdDeTai").val($(this).attr("id"));
            })
        })
    </script>
}
@if (ViewBag.mess != null)
{
    <script type="text/javascript">
        window.onload = function ()
        {
            this.toastr.success("@ViewBag.mess");
        }
    </script>
}
@if (Model == null)
{
    <div class="row">
        <div class="col">
            <div class="card card-default">
                <div class="card-header">
                    <p class="card-title col text-center text-danger">Chưa có dữ liệu.</p>
                </div>

            </div>
        </div>
    </div>
}
else
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <a asp-controller="DeTaiNghienCuu" asp-action="XuatBaoCaoTongQuat" class="btn btn-success btn-sm">Xuất báo cáo tổng quát</a>
                <a asp-controller="DeTaiNghienCuu" asp-action="XemLichSuDeTai" class="btn btn-danger btn-sm">Xem lịch sử đề tài</a>
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col-12">
                <div class="card card-primary">

                    @*CARD HEADER*@
                    <div class="card-header">
                        <h3 class="card-title">Danh sách đề tài trong đợt đăng ký (@Model.DotDangKyHienTai.ThoiGianBd.Value.ToString("dd/MM/yyyy") - @Model.DotDangKyHienTai.ThoiGianKt.Value.ToString("dd/MM/yyyy")) </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    @*CARD BODY*@
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-hover dataTable table-sm nowrap" role="grid" aria-describedby="example1_info">
                            <thead>
                                <tr role="row">
                                    <th tabindex="0" aria-controls="example1" rowspan="1">
                                        Mã đề tài
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Tên đề tài
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Mô tả
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Tệp đính kèm
                                    </th>
                                    <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                        Ngày lập
                                    </th>
                                    <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                        Giảng viên
                                    </th>
                                    <th tabindex="0" aria-controls="example1" rowspan="1">
                                        Tình trạng đăng ký
                                    </th>
                                    <th tabindex="0" aria-controls="example1" rowspan="1">
                                        Tình trạng đề tài
                                    </th>
                                    <th>

                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.listDeTaiHienTai)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.TenDeTai</td>
                                        <td>@item.MoTa</td>
                                        <td><a href="~/FileUpload/DeTaiNghienCuu/@item.TepDinhKem" download="@item.TepDinhKem">@item.TenTep</a></td>
                                        <td>@item.NgayLap.Value.ToString("dd/MM/yyyy")</td>
                                        @if (item.IdgiangVien != null)
                                        {
                                            <td>@(item.IdgiangVienNavigation.Ho + " " + item.IdgiangVienNavigation.Ten)</td>
                                        }
                                        else
                                        {
                                            <td><a>Chưa có GVHD</a></td>
                                        }

                                        @if (item.TinhTrangDangKy == 0)
                                        {
                                            <td>Đã đăng ký</td>
                                        }
                                        else
                                        {
                                            <td>Chưa đăng ký</td>
                                            <td>Chưa thực hiện</td>
                                        }

                                        @if (item.TinhTrangDeTai == (int)StatusDeTai.HoanThanh)
                                        {
                                            <td>Hoàn thành</td>
                                        }
                                        else if (item.TinhTrangDeTai == (int)StatusDeTai.Huy)
                                        {
                                            <td>Hủy</td>
                                        }
                                        else if (item.TinhTrangDeTai == (int)StatusDeTai.DaDangKy || item.TinhTrangDeTai == (int)StatusDeTai.DanhGiaLai)
                                        {
                                            <td>Đang thực hiện</td>
                                        }
                                        <td><a asp-controller="DeTaiNghienCuu" asp-action="XuatBaoCaoChiTietDeTai" asp-route-id="@item.Id" class="btn btn-primary btn-xs" title="Báo cáo chi tiết"><i class="fas fa-download"></i></a></td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card card-warning">
                    @*CARD HEADER*@
                    <div class="card-header">
                        <h3 class="card-title">Danh sách đề tài đề xuất</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>

                    @*CARD BODY*@
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover dataTable table-sm nowrap" style="width:100%" role="grid" aria-describedby="example1_info">
                            <thead>
                                <tr role="row">
                                    <th tabindex="0" aria-controls="example1" rowspan="1">
                                        Mã đề tài
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Tên đề tài
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Mô tả
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Tệp đính kèm
                                    </th>
                                    <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                        Ngày lập
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        MSSV đề xuất
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                        Giảng viên
                                    </th>

                                    <th tabindex="0" aria-controls="example1" rowspan="1">
                                        Tình trạng
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.listDeTaiDeXuatHienTai)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.TenDeTai</td>
                                        <td>@item.MoTa</td>
                                        <td><a href="~/FileUpload/DeTaiNghienCuu/@item.TepDinhKem" download="@item.TepDinhKem">@item.TenTep</a></td>
                                        <td>@item.NgayLap.Value.ToString("dd/MM/yyyy")</td>
                                        <td>@item.IdNguoiDangKy</td>
                                        @if (item.IdgiangVien != null)
                                        {
                                            <td><button id="@item.Id" class="btn btn-success btn-sm btnPhanCong" data-toggle="modal" data-target="#modal-PhanCongGVHD">@(item.IdgiangVienNavigation.Ho + " " + item.IdgiangVienNavigation.Ten) </button></td>
                                        }
                                        else
                                        {
                                            <td><button id="@item.Id" class="btn btn-warning btn-sm btnPhanCong" data-toggle="modal" data-target="#modal-PhanCongGVHD">Chưa có GVHD</button></td>
                                        }

                                        @if (item.TinhTrangDeTai == 3)
                                        {
                                            <td>Đã đăng ký</td>
                                        }
                                        else
                                        {
                                            <td>Chưa đăng ký</td>
                                        }
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modal-PhanCongGVHD">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header bg-navy">
                    <h3 class="card-title">Phân công giảng viên</h3>
                    <button type="button" class="close btn btn-tool" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-controller="DeTaiNghienCuu" asp-action="PhanCongGiangVien">
                        <input type="number" id="IdDeTai" name="IdDeTai" hidden />
                        <div class="form-group">
                            <label>Chọn giảng viên</label>
                            <select id="IdGiangVien" name="IdGiangVien" class="form-control"
                                    asp-items="@Model.listGiangVien">
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success">Phân công</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
}

KLTN/Areas/Admin/Views/DeTaiNghienCuu/XemLichSuDeTai.cshtml
@model IEnumerable<DeTaiNghienCuu>
@{
    ViewData["Title"] = "XemLichSuDeTai";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Script
{
    <script>
        $(document).ready(function ()
        {
            $(document).on("click", ".btnXemNhom", function ()
            {
                var id = $(this).attr("id");
                $("#modal-NhomSV .modal-body").html("");
                $.get('/Admin/DetaiNghienCuu/XemNhom/' + id, function (content)
                {
                    $("#modal-NhomSV .modal-body").html(content);
                    $("#modal-NhomSV").modal();
                });
            })
        })
    </script>
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card card-danger">

                @*CARD HEADER*@
                <div class="card-header">
                    <h3 class="card-title">Lịch sử đề tài nghiên cứu</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>

                @*CARD BODY*@
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-hover dataTable table-sm nowrap" role="grid" aria-describedby="example1_info">
                        <thead>
                            <tr role="row">
                                <th tabindex="0" aria-controls="example1" rowspan="1">
                                    Mã đề tài
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                    Tên đề tài
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                    Mô tả
                                </th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1">
                                    Tệp đính kèm
                                </th>
                                <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                    Ngày lập
                                </th>
                                <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                    Nhóm thực hiện
                                </th>
                                <th class="sorting_desc" tabindex="0" aria-controls="example1" rowspan="1">
                                    Giảng viên
                                </th>
                                <th tabindex="0" aria-controls="example1" rowspan="1">
                                    Tình trạng đề tài
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.TenDeTai</td>
                                <td>@item.MoTa</td>
                                <td><a href="~/FileUpload/DeTaiNghienCuu/@item.TepDinhKem" download="@item.TepDinhKem">@item.TenTep</a></td>
                                <td>@item.NgayLap.Value.ToString("dd/MM/yyyy")</td>
                                <td><button id="@item.Id" class="btn btn-sm btn-danger btnXemNhom"><i class="fas fa-user-friends"></i> Xem nhóm </button></td>
                                @if (item.IdgiangVien != null)
                                {
                                    <td>@(item.IdgiangVienNavigation.Ho + " " + item.IdgiangVienNavigation.Ten)</td>
                                }
                                else
                                {
                                    <td><a>Chưa có GVHD</a></td>
                                }

                                @if (item.TinhTrangDeTai == (int)StatusDeTai.HoanThanh)
                                {
                                    <td>Hoàn thành</td>
                                }
                                else
                                {
                                    <td>Hủy</td>
                                }
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <a asp-controller="DeTaiNghienCuu" asp-action="Index" class="btn btn-danger btn-sm">trở về</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-NhomSV">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-navy">
                <h3 class="card-title">Thông tin nhóm thực hiện</h3>
                <button type="button" class="close btn btn-tool" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div class="modal-body">
            </div>
            @*@await Html.PartialAsync("_ValidationScriptsPartial")*@
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>